In [5]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, cohen_kappa_score
import numpy as np
from sklearn.metrics import f1_score

In [6]:
df = pd.read_csv('C:/Users/USER/OneDrive - The University of Memphis/Khulna University/Paper-3/Processed/Excel/Confusion2022.csv')
true_labels = df['GrndTrth']
predicted_labels = df['Classified']

In [7]:
conf_matrix = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[150   0   0   0   0   0]
 [  0 147   0   0   3   0]
 [  0   0 150   0   0   0]
 [  0   0   1 148   1   0]
 [  0   3   0   0 147   0]
 [  0   0   1   0   1 148]]


In [8]:
producer_accuracy = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)
user_accuracy = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)

print("\nProducer Accuracy (Recall):", producer_accuracy)
print("User Accuracy (Precision):", user_accuracy)



Producer Accuracy (Recall): [1.         0.98       1.         0.98666667 0.98       0.98666667]
User Accuracy (Precision): [1.         0.98       0.98684211 1.         0.96710526 1.        ]


In [9]:
overall_accuracy = accuracy_score(true_labels, predicted_labels)
print("\nOverall Accuracy:", overall_accuracy)



Overall Accuracy: 0.9888888888888889


In [10]:
kappa = cohen_kappa_score(true_labels, predicted_labels)
print("\nKappa Statistic:", kappa)



Kappa Statistic: 0.9866666666666667


In [11]:
# Calculate F1 Score for each class (micro, macro, weighted)
f1_micro = f1_score(true_labels, predicted_labels, average='micro')
f1_macro = f1_score(true_labels, predicted_labels, average='macro')
f1_weighted = f1_score(true_labels, predicted_labels, average='weighted')

print("F1 Score (Micro):", f1_micro)
print("F1 Score (Macro):", f1_macro)
print("F1 Score (Weighted):", f1_weighted)

F1 Score (Micro): 0.9888888888888889
F1 Score (Macro): 0.9889107664044327
F1 Score (Weighted): 0.9889107664044328
